# -*- coding: utf-8 -*-
"""first_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sl39zao0HmLqYeaHTL41_GtNX_-FUSCh

# File to read and clean the data, exporting the data into other files.
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

betb011_22 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_42647_2022_timeseries.csv")
betb011_23 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_42647_2023_timeseries.csv")

betr012_22 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_42119_2022_timeseries.csv")
betr012_23 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_42119_2023_timeseries.csv")

betb004_22 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_42253_2022_timeseries.csv")
betb004_23 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_42253_2023_timeseries.csv")

betr001_22 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_41247_2022_timeseries.csv")
betr001_23 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_41247_2023_timeseries.csv")

betmeu1_22 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_61521_2022_timeseries.csv")
betmeu1_23 = pd.read_csv("/content/drive/My Drive/DataThesis/BE_7_61521_2023_timeseries.csv")

betb011 = pd.concat([betb011_22,betb011_23])
betr012 = pd.concat([betr012_22,betr012_23])
betb004 = pd.concat([betb004_22,betb004_23])
betr001 = pd.concat([betr001_22,betr001_23])
betmeu1 = pd.concat([betmeu1_22,betmeu1_23])

columns_remove = ['AirPollutant','DatetimeEnd','AirQualityStationEoICode','AirQualityStation','Countrycode','Namespace','AirQualityNetwork','SamplingProcess','SamplingPoint','Sample','AirPollutantCode','AveragingTime','UnitOfMeasurement','Validity','Verification']
ozone_betb011 = betb011.drop(columns=columns_remove)
ozone_betr012 = betr012.drop(columns=columns_remove)
ozone_betb004 = betb004.drop(columns=columns_remove)
ozone_betr001 = betr001.drop(columns=columns_remove)
ozone_betmeu1 = betmeu1.drop(columns=columns_remove)

dfs = [ozone_betb011,ozone_betr012,ozone_betb004,ozone_betr001,ozone_betmeu1]

for df in dfs:
  df['DatetimeBegin'] = df['DatetimeBegin'].str[:-7]
  df['DatetimeBegin'] = pd.to_datetime(df['DatetimeBegin'])

ozone_betb011.to_csv("/content/drive/My Drive/DataThesis/ozone_betb011.csv", index=False)
ozone_betr012.to_csv("/content/drive/My Drive/DataThesis/ozone_betr012.csv", index=False)
ozone_betb004.to_csv("/content/drive/My Drive/DataThesis/ozone_betb004.csv", index=False)
ozone_betr001.to_csv("/content/drive/My Drive/DataThesis/ozone_betr001.csv", index=False)
ozone_betmeu1.to_csv("/content/drive/My Drive/DataThesis/ozone_betmeu1.csv", index=False)